### ISSUE TITLE
improve google action performance

### ISSUE THREAD

**Issue by hyzhak** [internetarchive/internet-archive-voice-apps#318]
it seems app startups longer then expected:

Here is an example of one request, which failed because of timeout (it took 8458 ms):
```
7:49:15.615 PM - Function execution started
1s before 1st log
7:49:16.202 PM - 1st log message
4s build app
7:49:20.702 PM - ia:start:debug [Start]
1s preparing
7:49:21.770 PM – begin handling
2s handling
7:49:23.926 PM – end handling
0.1s to send a response back
7:49:24.072 PM - Function execution took 8458 ms, finished with status code: 200
```

full log: https://console.firebase.google.com/u/0/project/internet-archive/functions/logs?search=uuk1kjpyfdd3&severity=DEBUG

Filter logs to get `Function execution time` https://console.firebase.google.com/u/0/project/internet-archive/functions/logs?search=Function%20execution%20took&severity=DEBUG

**Comment by hyzhak** [comment]
I have sent mail to Firebase support:

> Hello Firebase team!
> 
> We have Action of Google app which is hosted as Firebase Functions. And recently I found that it restarts (cold start) each request. 
> Because it is node.js cold start is very bad for performance, Node.js much more effective when it persists between sessions (we don't need to reload modules and preprocess some data):
> each restart took about 3-4 seconds to restart, and about 0,5 - 6 seconds to process a request (application layer)
> as result sometimes it took almost 10 seconds, What is the critical for Dialog flow which considers what our app isn't available.
> 
> 
> # Question:
> 
> I don't see any significant reasons why Firebase restarts our app, Is there any way to find signals which triggered the cold starts? And could I ask Firebase decrease probability of such restarting? Ideally, Firebase could ask app whether it ready to restart - and restart when it is agreed or restart app in advance.
> 
> 
> # Params:
> 
> - node.js app
> - app uses less than 50MB
> - we got about 1 request minute
> - we very rarely have unhandled exception less than 1 in a week
> 
> In additional I have found that once in a 20 request firebase functions doesn't restart app - but I haven't found any reasons why it works that moment. It seems just like some lucky moment.
> 
> Best,
> - Eugene

**Comment by hyzhak** [comment]
I got a response to the mail:

> Hi Eugene,
> 
> This is Phoebe from Firebase support, and I'm happy to help you out with the issue you're having in Cloud Functions.
> 
> I am now looking into this, and I'll get back to you within a day or two to provide updates or if I need additional information on your end.
> 
> Sincerely,
> Phoebe

**Comment by hyzhak** [comment]
asked the same question in [Firebase Google Group](https://groups.google.com/forum/#!topic/firebase-talk/MZjwG3XEKus)

**Comment by hyzhak** [comment]
Sometimes Firebase doesn't restart app and it works fine:
<img width="768" alt="without cold start" src="https://user-images.githubusercontent.com/184706/44105625-90bff362-9ff2-11e8-85b1-0be13d58f993.png">

But then again it fails in Cold start
<img width="771" alt="with cold start" src="https://user-images.githubusercontent.com/184706/44105663-a834ddb4-9ff2-11e8-8703-693549e52148.png">

**Comment by hyzhak** [comment]
I got response from the Firebase team:

> Hi Eugene,
> 
> According to our engineers, there has been a possible change that might have affected cold starts. It has been recently rolled back. Could you try again and let me know if you're still encountering issues? If so, could you provide the following information so I can investigate more on the issue:
> - Detailed description and steps on what your functions is doing (Eg. What's the data being processed).
> - Location where your functions is being triggered from
> - Screenshot of your functions' logs showing the issue.
> - A minimal complete verifiable example that reproduces the issue. You may send it as a zip file, or create a shareable link that I can access in Google Drive.
> - Detailed or step by step instructions to reproduce the issue.
> Any other extra information that you could share would be very helpful. Looking forward to your response.
> 
> Sincerely,
> Phoebe

And I'd like to tell that really few days ago we stop experience cold start problem. So Firebase team fixed the problem.

**Comment by yagyanshbhatia** [comment]
Should we close this issue?
or do you want to still improve performance even after https://github.com/internetarchive/internet-archive-voice-apps/issues/405
If yes, in what ways??

**Comment by hyzhak** [comment]
@yagyanshbhatia those issues cover different parts of performance. And this issue could be close because reflect issue which we had on Google side. So thank you to mark it here
