### ISSUE TITLE
Problem in startup

### ISSUE THREAD

**Issue by vigneshtdev** [internetarchive/internet-archive-voice-apps#446]
HI I have followed the setup in README, but now when I run it with `DEBUG=ia* sudo npm start`, the following error shows up in the ocnsole::

```info: User function triggered, starting execution
error: TypeError: Cannot read property 'type' of undefined
    at module.exports (/home/vignesh/internet-archive-voice-apps/functions/src/platform/assistant/middlewares/log-empty-session-data.js:14:57)
    at Function.<anonymous> (/home/vignesh/internet-archive-voice-apps/functions/node_modules/actions-on-google/dist/service/dialogflow/dialogflow.js:123:32)
    at Generator.next (<anonymous>)
    at fulfilled (/home/vignesh/internet-archive-voice-apps/functions/node_modules/actions-on-google/dist/service/dialogflow/dialogflow.js:19:58)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
info: Execution took 789 ms, user function completed successfully
```
And when I visit http://localhost:5000/internet-archive-7c9e1/us-central1/assistant then following json shows up

``` // 20190126103250
// http://localhost:5000/internet-archive-7c9e1/us-central1/assistant

{
  "error": "Cannot read property 'type' of undefined"
}
```

**Comment by vigneshtdev** [comment]
@hyzhak Is this an excepted behavior?

**Comment by hyzhak** [comment]
@vigneshtdev  yes, it is expected, but maybe isn't desired and it could have much more graceful error response. But anyway you don't need to visit http://localhost:5000/internet-archive-7c9e1/us-central1/assistant, have you tried to follow next steps?

**Comment by vigneshtdev** [comment]
Hey if you aren't working on it, can you assign me #441

**Comment by hyzhak** [comment]
@vigneshtdev it is almost done

**Comment by vigneshtdev** [comment]
@hyzhak  any other issue I can help out with, most of them are assigned to you

**Comment by hyzhak** [comment]
@vigneshtdev [the most part of issues](https://github.com/internetarchive/internet-archive-voice-apps/issues?q=is%3Aopen+is%3Aissue+no%3Aassignee ) aren't assigned to me ;)

But I'd recommend to start env first than try to solve any issue from [good first issue list](https://github.com/internetarchive/internet-archive-voice-apps/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22)

**Comment by anuragiiits** [comment]
> HI I have followed the setup in README, but now when I run it with `DEBUG=ia* sudo npm start`, the following error shows up in the ocnsole::
> 
> ```
> error: TypeError: Cannot read property 'type' of undefined
>     at module.exports (/home/vignesh/internet-archive-voice-apps/functions/src/platform/assistant/middlewares/log-empty-session-data.js:14:57)
>     at Function.<anonymous> (/home/vignesh/internet-archive-voice-apps/functions/node_modules/actions-on-google/dist/service/dialogflow/dialogflow.js:123:32)
>     at Generator.next (<anonymous>)
>     at fulfilled (/home/vignesh/internet-archive-voice-apps/functions/node_modules/actions-on-google/dist/service/dialogflow/dialogflow.js:19:58)
>     at processTicksAndRejections (internal/process/next_tick.js:81:5)
> info: Execution took 789 ms, user function completed successfully
> ```
> And when I visit http://localhost:5000/internet-archive-7c9e1/us-central1/assistant then following json shows up
> 
> ```
> // http://localhost:5000/internet-archive-7c9e1/us-central1/assistant
> 
> {
>   "error": "Cannot read property 'type' of undefined"
> }
> ```

Hey, I am also getting the exact same Error for any request that is sent from Dialogflow. Can anyone tell me what have I missed?
