### ISSUE TITLE
Assistant goes into a loop when selected instrumental genre

### ISSUE THREAD

**Issue by yagyanshbhatia** [internetarchive/internet-archive-voice-apps#447]
![image](https://user-images.githubusercontent.com/26413062/52032693-10214680-2548-11e9-8d9d-4f27784ebb53.png)

**Comment by hyzhak** [comment]
@yagyanshbhatia thank you, it seems degradation on DialogFlow model, I'll take a look

**Comment by hyzhak** [comment]
according to logs for some reasons DialogFlow match "Instrumental" to `"no"` action

**Comment by hyzhak** [comment]
Ok, Issue is solved.

Btw. we don't have any training phrase even close to "instrumental" in "no" intent, so I solved it by explicitly defining "Instrumental" as training phrase for `music-query-subject` intent.

@yagyanshbhatia if you can confirm it on your side, pls close this issue

**Comment by yagyanshbhatia** [comment]
@hyzhak Yes, its resolved now. Closing this issue.
