### ISSUE TITLE
TypeError: Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by hyzhak** [internetarchive/internet-archive-voice-apps#457]
Logs

> TypeError: Cannot read property 'type' of undefined
>     at module.exports (/srv/src/platform/assistant/middlewares/log-empty-session-data.js:14:57)
>     at Function.<anonymous> (/srv/node_modules/actions-on-google/dist/service/dialogflow/dialogflow.js:123:32)
>     at Generator.next (<anonymous>)
>     at fulfilled (/srv/node_modules/actions-on-google/dist/service/dialogflow/dialogflow.js:19:58)
>     at <anonymous>
>     at process._tickDomainCallback (internal/process/next_tick.js:229:7)

**Comment by anuragiiits** [comment]
Hey, I just figured out there is no such issue with invoking the action with Google Assistant.
This error pops up only when the request is made from DialogFlow query box. The JSON request through DialogFlow has nothing(empty) in `conv.request`, hence `conv.request.conversation` is `undefined` which leads to the above error at line 14 of **log-empty-session-data.js**
However, when the request is made from Google Assistant (Device/Simulator), `conv.request` has all the desired parameters and everything is working perfectly.
So, do you think is it really a bug? Invocation from Dialogflow is never required, right?

**Comment by anuragiiits** [comment]
@hyzhak  Can you please address my above comment?

**Comment by hyzhak** [comment]
Don't see that error for a long time. Because it was inside of dialog flow it might disappear with few last updates.
