### ISSUE TITLE
No support for deployment to Google Cloud Functions

### ISSUE THREAD

**Issue by alphadose** [internetarchive/internet-archive-voice-apps#461]
This warning is shown whenever **firebase serve** is executed locally
```
Warning: You're using Node.js v9.10.1 but Google Cloud Functions only supports v6.11.5.
```
The current codebase uses **async/await** which is not available in Node.js v6.11.5 and hence the current codebase cannot be deployed to Google Cloud Functions.
Transpilation of the entire codebase to ES5 syntax and async-to-generator is necessary before deployment.

**Comment by agharshit08** [comment]
Actually, they get deployed successfully for me.

**Comment by alphadose** [comment]
@agharshit08 You must be talking about Firebase. Firebase runs Node.js 8 which supports async/await and hence we can successfully deploy the application to Firebase which you did in your case.
What I am addressing in this issue is Google Cloud Functions not Firebase. The Google Cloud Functions run Node v6.11.5 which doesn't have async/await support and hence the codebase requires transpilation to ES5 using babel or something before deployment.

**Comment by agharshit08** [comment]
I am talking about cloud functions that we deploy using firebase deploy

**Comment by alphadose** [comment]
**firebase deploy** deploys the application to the firebase cloud. The firebase cloud runs Node.js 8 and has no problems with the async/await syntax.
We can deploy the application to Firebase Cloud but not to Google Cloud Functions because it runs Node.js 6.11.5. Hence we need Babel for this.

**Comment by agharshit08** [comment]
Got you, I thought you were referring to firebase functions

**Comment by hyzhak** [comment]
@alphadose do you really need pure "Google Cloud Functions". And if so, it has node.js v8 https://cloud.google.com/functions/docs/concepts/nodejs-8-runtime
