### ISSUE TITLE
Project Idea #2 for GSoC 2019

### ISSUE THREAD

**Issue by ImRaviTejaG** [internetarchive/internet-archive-voice-apps#463]
In the project idea #2: Continue development of the Google Assistant Action "Internet Archive", the features to be developed include:

- More natural voice Interactions
- Logging of all errors and user interactions
- Use of all logs to identify opportunities to improve the service
- Improving the service based on identified opportunities
- Adding visual interfaces for emerging devices with screens
- Adding support for reading books
- Adding support for integration with the Wayback Machine

Can the potential mentors please elaborate the milestones and deliverables of the issue further as it would be quite helpful for the candidates.

@hyzhak Please have a look sir.

**Comment by Zerichen** [comment]
I am wondering if the potential mentor for this idea is active or not?

**Comment by ImRaviTejaG** [comment]
@hyzhak Can you please answer the above queries?!

**Comment by hyzhak** [comment]
@ImRaviTejaG You have added list of proposed features from [here](https://docs.google.com/document/d/1posF4zhq2lAz7eikloT9_K4LnHXfJ5VWGpCtJS6rJ0M/edit) and now it's your part of job to come up with your proposal what do you want to implement here and your milestones estimation based on your performance.
