### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by akshat14714** [internetarchive/internet-archive-voice-apps#493]
OS : Ubuntu 18.04
Node : 8.17.0
NVM : 0.33.11
Firebase : 7.14.0

While installing, I am facing the following issues:
- In the ```DEBUG=ia:* npm start``` step, I am getting a message regarding no functions emulated.
While checking the firebase logs using the command ```firebase functions:log```, I am getting No log entries found.

![Screenshot from 2020-03-04 17-42-14](https://user-images.githubusercontent.com/23234318/75879049-abb67200-5e40-11ea-8571-6438e838a15b.png)

**Comment by ishank-dev** [comment]
Did you update ``functions/.runtimeconfig.json`` with the fake keys?

**Comment by akshat14714** [comment]
@ishank-dev Yes, I updated the ```functions/.runtimeconfig.json``` with the fake keys, and still, I am getting the same error.

**Comment by ishank-dev** [comment]
Ensure 3 things
1.``.firebaserc`` has the same name as the name of your firebase project
2. Check whether you are logged into the right firebase account.
3. Ensure that you have used ``firebase init`` before adding your own project 
For me, the app runs properly and a JSON is returned.
I am just figuring a way out to run the ``How it works on google assistant`` part.
Will update here once I figure it out

**Comment by ishank-dev** [comment]
It's running without any issues. Figured out google assistant part as well.
![Screenshot_20200305_225302](https://user-images.githubusercontent.com/45262592/76007568-42179000-5f34-11ea-81e6-fe720560e323.png)

**Comment by akshat14714** [comment]
@ishank-dev I tried all the steps as you told me once again and everything was setup nicely, but when I am running the command ```DEBUG=ia:* npm start``` I am still getting ```No functions emulated```.
Is there any other reason due to which this could occur?

**Comment by ishank-dev** [comment]
@akshat14714  It seems the error is with the compatibility of your dependencies with the cloud functions.
In order to run it, your firebase-admin should be version 8.0 or higher. Refer the below link -
https://firebase.google.com/docs/functions/local-emulator
My suggestion will be to upgrade all of your dependencies and run it again.
Check the [issue #770](https://github.com/firebase/firebase-tools/issues/770) as well

I am sharing my package.json file might help in knowing the right version you need to install.
```{
  "name": "audio-interface-of-internet-archive",
  "description": "Audio Interface of Internet Archive",
  "version": "2.5.15",
  "private": true,
  "author": "Internet Archive",
  "license": "AGPL-3.0",
  "engines": {
    "node": "8"
  },
  "scripts": {
    "lint": "eslint ./",
    "uploader": "node ./uploader",
    "mocha": "mocha --opts ./tests/mocha.opts",
    "start": "firebase serve --only functions:assistant",
    "start:alexa": "bst proxy lambda index-alexa",
    "deploy": "firebase deploy --only functions:assistant",
    "test": "npm run lint && npm run mocha"
  },
  "dependencies": {
    "actions-on-google": "^2.12.0",
    "alexa-sdk": "^1.0.25",
    "ask-sdk": "^2.7.0",
    "axios": "^0.19.0",
    "bespoken-tools": "^2.4.24",
    "dashbot": "^11.1.0",
    "debug": "^4.1.1",
    "firebase-admin": "^8.9.0",
    "firebase-functions": "^3.3.0",
    "glob": "^7.1.6",
    "hirestime": "^4.0.0",
    "lodash": "^4.17.15",
    "mathjs": "^5.10.3",
    "moment": "^2.24.0",
    "mustache": "^2.3.2",
    "node-fetch": "^2.6.0",
    "raven": "^2.6.4",
    "replaceall": "^0.1.6",
    "uuid": "^3.3.3"
  },
  "devDependencies": {
    "axios-mock-adapter": "^1.17.0",
    "chai": "^4.2.0",
    "eslint": "^6.8.0",
    "eslint-config-semistandard": "^15.0.0",
    "eslint-config-standard": "^14.1.0",
    "eslint-plugin-chai-friendly": "^0.5.0",
    "eslint-plugin-import": "^2.19.1",
    "eslint-plugin-mocha": "^6.2.2",
    "eslint-plugin-node": "^11.0.0",
    "eslint-plugin-promise": "^4.2.1",
    "eslint-plugin-standard": "^4.0.1",
    "js-yaml": "^3.13.1",
    "mocha": "^6.2.2",
    "rewire": "^4.0.1",
    "sinon": "^8.0.1",
    "sinon-chai": "^3.4.0",
    "virtual-alexa": "^0.7.3"
  }
}

**Comment by chethansai** [comment]
Struck at same step of setup.

**Comment by akshat14714** [comment]
@ishank-dev I was successful in running the application. There was an issue with the node version.
Node version: 8.16
Firebase version: 7.14.0
