### ISSUE TITLE
How to check if my project is working or not?

### ISSUE THREAD

**Issue by mathhewhayden** [internetarchive/internet-archive-voice-apps#502]
After following the steps..How to check if the project changes are being reflected or not?

**Comment by chethansai** [comment]
You gotta try out various modeules of prjoect,make changes and try tests.
For suppouse..

type welcome in google assistant test
It reponds  <speak>Welcome to the music at the Internet Archive. Want to listen to 78s, Live concerts, Unlocked Recordings or Christmas music?</speak>

Now go to internet-archive-voice-apps\functions\src\strings.js
Find the text: welcome change acknowledge >Welcome to music at the Internet Archive(removing the)
type welcome in google assistant test
You will find the changes reflected as:<speak>Welcome to  music at the Internet Archive. Want to listen to 78s, Live concerts, Unlocked Recordings or Christmas music?</speak>

**Comment by mathhewhayden** [comment]
Thanks mate for the suppourt.
